namespace YgomSystem.Network
{
	public enum MissionCode
	{
		NONE = 0,
		ERROR = 1,
		FATAL = 2,
		CRITICAL = 3,
		ERROR_INVALID_POOL = 2601,
		ERROR_INVALID_MISSION = 2602,
		ERROR_OUT_OF_TERM_POOL = 2603,
		ERROR_OUT_OF_TERM_MISSION = 2604,
		ERROR_GET_REWARD_MASTER = 2611,
		ERROR_GET_PROGRESS = 2612,
		ERROR_ALREADY_RECEIVE = 2613,
		ERROR_ILLEGAL_RECEIVE = 2614,
		ERROR_ILLEGAL_PROGRESS = 2615,
		ERROR_NON_APPLY_REWARD = 2616
	}
}
