namespace YgomSystem.Network
{
	public enum RoomCode
	{
		NONE = 0,
		ERROR = 1,
		FATAL = 2,
		CRITICAL = 3,
		ERR_INVALID_ROOM = 3101,
		ERR_ENTRY_FAILED = 3102,
		ERR_INVALID_NEW_ROOM_ID = 3103,
		ERR_NO_VACANT_TABLES = 3104,
		ERR_INVALID_DECKSET = 3105,
		ERR_ROOM_CREATE_FAILED = 3106,
		ERR_USER_BLOCK = 3107,
		ERR_INVALID_DATA = 3108,
		ERR_PLATFORM_AUTH_EXPIRED = 3109,
		ERR_ALREADY_ENTRY_ROOM = 3110,
		ERR_ROOM_MEMBER_MAX = 3111,
		ERR_RIVAL_LEAVE_TABLE = 3112,
		ERR_ENTRY_ROOM_CROSS_INVALID = 3113,
		ERR_ENTRY_ROOM_CROSS_PF_INVALID = 3114,
		ERR_ENTRY_ROOM_CROSS_XB_BOTH_INVALID = 3115,
		ERR_ENTRY_ROOM_CROSS_XB_DEVICE_INVALID = 3116,
		ERR_ENTRY_ROOM_CROSS_XB_APP_INVALID = 3117,
		ERR_ENTRY_ROOM_CROSS_PF_APP_INVALID = 3118,
		ERR_ENTRY_ROOM_VALID_CROSS_XB_BOTH_INVALID = 3119,
		ERR_ENTRY_ROOM_VALID_CROSS_XB_DEVICE_INVALID = 3120,
		ERR_ENTRY_ROOM_VALID_CROSS_XB_APP_INVALID = 3121,
		ERR_ENTRY_ROOM_VALID_CROSS_PF_APP_INVALID = 3122,
		ERR_DECK_EMPTY = 3123,
		ERR_DECK_REG = 3124,
		ERR_LIMIT_REGULATION_PERIOD = 3125,
		ERR_HOST_CLIENT_VERSION = 3126
	}
}
