namespace YgomGame.TextIDs
{
	public enum IDS_DUELPASS
	{
		TITLE = 0,
		BRIEFDESC = 1,
		TIMELIMIT = 2,
		WHATISDUELPASS = 3,
		RECEIVEALL = 4,
		PURCHASEATSHOP = 5,
		DUELPASSREWARDLIST = 6,
		GOLDPASSITEMSUM = 7,
		GOLDPASSITEMLIST = 8
	}
}
