namespace YgomGame.TextIDs
{
	public enum IDS_PUBLICDECKSEARCH
	{
		TITLE = 0,
		ADD_CATEGORY = 1,
		ADD_TAG = 2,
		CATEGORY_TITLE = 3,
		TAG_TITLE = 4,
		NULL_DECK = 5,
		TOO_MANY_CARDS = 6,
		NULL_CATEGORY_MESSAGE = 7,
		NULL_TAG_MESSAGE = 8,
		NULL_GUIDE = 9,
		CAT_FILTER_DESC = 10,
		TAG_FILTER_DESC = 11,
		FILTER = 12,
		FILTER_DESC = 13,
		COPY_NOTES = 14,
		MAINTE = 15,
		NOTES = 16
	}
}
