namespace YgomGame.TextIDs
{
	public enum IDS_ENQUETE
	{
		REVIEW_TITLE = 0,
		REVIEW_MESSAGE = 1,
		REVIEW_TO_CHEER = 2,
		REVIEW_TO_VOICE = 3,
		REVIEW_NOT_NOW = 4,
		REVIEW_VOICE_TITLE = 5,
		REVIEW_VOICE_MESSAGE = 6,
		REVIEW_VOICE_TO_ENQUETE = 7,
		REVIEW_VOICE_TO_SUPPORT = 8,
		REVIEW_LAST_MESSAGE = 9
	}
}
