namespace YgomGame.TextIDs
{
	public enum IDS_LOGINBONUS
	{
		TITLE = 0,
		ERR_TITLE = 1,
		REWARD_LIMIT = 2,
		ANNIV_1ST_TITLE = 3,
		ANNIV_1ST_DESC = 4,
		GOTO_1ST_ANNIVPACK = 5,
		ERR_INVALID_TERM = 6,
		ERR_ALREADY_RECEIVED = 7,
		ERR_COMPLETED = 8,
		ERR_4005 = 9,
		YUGIOH_25TH_TITLE = 10,
		YUGIOH_25TH_DESC = 11,
		ANNIV_2ND_DESC = 12,
		YUGIOH_6000DL_TITLE = 13,
		YUGIOH_6000DL_DESC = 14,
		WELCOME_COMEBACK_TITLE = 15,
		YUGIOH_WELCOME_COMEBACK_DESC = 16,
		YUGIOH_QUALIFYING_TITLE = 17,
		YUGIOH_QUALIFYING_DESC = 18
	}
}
