namespace YgomGame.TextIDs
{
	public enum IDS_FREE
	{
		TITLE = 0,
		TITLENOTE = 1,
		MENU_INFO = 2,
		MENU_HISTORY = 3,
		INFOTITLE = 4,
		INFO = 5,
		DECK_SELECT = 6,
		DECK_RENT = 7,
		DECK_MY = 8,
		INFO_HEAD = 9,
		INFO_RULE_TITLE = 10,
		INFO_SAVE_TITLE = 11,
		INFO_REG_TITLE = 12,
		INFO_CAUTION_TITLE = 13,
		INFONOTE = 14,
		REG_INFO = 15,
		INFO_SAVE_DETAIL = 16,
		INFO_SAVE_DETAIL2 = 17,
		CANNOT_USETAG = 18,
		CANNOT_USE = 19,
		CANNOT_ABOUT2 = 20,
		CANNOT_ABOUT3 = 21,
		TEMPID_1 = 22,
		TEMPID_2 = 23,
		TEMPID_3 = 24,
		TEMPID_4 = 25
	}
}
